import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

// Importar las fuentes Ebrima y Ebrima-Bold
const ebrima = localFont({
  src: "./fonts/ebrima.woff",
  variable: "--font-ebrima",
  weight: "normal",
});
const ebrimaBold = localFont({
  src: "./fonts/ebrima-bold.woff",
  variable: "--font-ebrima-bold",
  weight: "bold",
});

export const metadata = {
  title: "Financial.lly",
  description: "Generated by Financial.lly",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${ebrima.variable} ${ebrimaBold.variable} antialiased`}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}